all:
	g++ -std=c++11 -g -o L1simulate CacheLine.cpp CacheSet.cpp Cache.cpp mesi.cpp Processor.cpp Bus.cpp L1simulate.cpp
run1:
	./L1simulate -t app1 -s 6 -E 2 -b 5 -o abcd.txt

run2:
	./L1simulate -t app2 -s 5 -E 2 -b 5 -o abcd.txt

run3:
	./L1simulate -t app3 -s 4 -E 2 -b 5 -o abcd.txt

run4:
	./L1simulate -t app4 -s 5 -E 2 -b 5 -o abcd.txt

run5:
	./L1simulate -t app5 -s 5 -E 2 -b 5 -o abcd.txt

run6:
	./L1simulate -t app6 -s 5 -E 2 -b 5 -o abcd.txt

run7:
	./L1simulate -t app7 -s 5 -E 2 -b 5 -o abcd.txt

run8:
	./L1simulate -t app8 -s 6 -E 2 -b 5 -o abcd.txt

our1:
	./L1simulate -t our1 -s 2 -E 2 -b 5 -o abcd.txt

our2:
	./L1simulate -t our2 -s 2 -E 2 -b 5 -o abcd.txt