all:
	g++ -std=c++11 -g -o L1simulate CacheLine.cpp CacheSet.cpp Cache.cpp mesi.cpp Processor.cpp Bus.cpp L1simulate.cpp
run1:
	./L1simulate -t app1 -s 6 -E 2 -b 5 -o run1.txt

run2:
	./L1simulate -t app2 -s 6 -E 2 -b 5 -o run2.txt

run3:
	./L1simulate -t app3 -s 4 -E 2 -b 5 -o run3.txt

run4:
	./L1simulate -t app4 -s 5 -E 2 -b 5 -o run4.txt

run5:
	./L1simulate -t app5 -s 5 -E 2 -b 5 -o run5.txt

run6:
	./L1simulate -t app6 -s 5 -E 2 -b 5 -o run6.txt

run7:
	./L1simulate -t app7 -s 5 -E 2 -b 5 -o run7.txt

run8:
	./L1simulate -t app8 -s 6 -E 2 -b 5 -o run8.txt

our1:
	./L1simulate -t our1 -s 2 -E 2 -b 5 -o our1.txt

our2:
	./L1simulate -t our2 -s 2 -E 2 -b 5 -o our2.txt

false1:
	./L1simulate -t false1 -s 5 -E 1 -b 5 -o false1.txt

false1c:
	./L1simulate -t false1 -s 5 -E 1 -b 3 -o false1c.txt

false2:
	./L1simulate -t false2 -s 5 -E 1 -b 5 -o false2.txt

false2c:
	./L1simulate -t false2 -s 5 -E 1 -b 3 -o false2c.txt